version: 2.1
jobs:
    build:
       docker:
               - image: ubuntu:latest
       steps: 
         - checkout
         - run:
              name: Build Examples
              command: make
         - run:
              name: Run Executables
              command: ./test_binaries
